### ISSUE TITLE
interactive not working with IntelliJ runnerw.exe

### ISSUE THREAD

**Issue by caritasverein** [klaussinani/signale#55]
**Describe the bug**
Using the interactive demo, running this code will not work in JetBrains IDE's which are using runnerw.exe to run node.exe and the code.  

You will get the following error:

```
"C:\Program Files\JetBrains\PhpStorm 2018.1.6\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" D:\test\index.js
[interactive] » ...  awaiting  [1/4] - Process A
D:\test\node_modules\signale\signale.js:240
      stream.moveCursor(0, -1);
             ^

TypeError: stream.moveCursor is not a function
    at Signale._write (D:\test\node_modules\signale\signale.js:240:14)
    at _formatStream.forEach.stream (D:\test\node_modules\signale\signale.js:251:14)
    at Array.forEach (<anonymous>)
    at Signale._log (D:\test\node_modules\signale\signale.js:250:35)
    at Signale._logger (D:\test\node_modules\signale\signale.js:257:10)
    at Timeout.setTimeout [as _onTimeout] (D:\test\index.js:8:17)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

Process finished with exit code 1
```
It happens as soon as the second log message should appear.

**To Reproduce**
- Create a new project with the example code: https://gist.github.com/caritasverein/6cac926bc06b9fe074d057d6405896d9
- Use any JetBrains IDE on Windows using runnerw
- Run the code in the IDE

**Expected behavior**
Get a nice interactive output like in the signale project readme.md

**Technical Info**
 - OS: Windows 10 Build 1803 64 Bit
 - Signale Version: 1.2.1
 - Node.js Version: v8.11.3
 - IDE Version: PhpStorm 2018.1.6 (runnerw.exe Version 1.0.0.1)

I would be happy if i can help you testing in this case. Feel free to contact me 👋

**Comment by astronomersiva** [comment]
This happens to me while trying to deploy on Netlify as well.
